# SPDX-FileCopyrightText: 2026 GFZ Helmholtz Centre for Geosciences
# SPDX-FileContributor: Bernhard Haas
#
# SPDX-License-Identifier: Apache-2.0

"""The ``el-paso`` command line entry point.

Groups every recipe under :mod:`el_paso.recipes` into one command tree, one
sub-command group per mission::

    el-paso list
    el-paso poes meped --start-time 2013-03-16 --satellite noaa15
    el-paso rbsp mageis-electrons --mag-field TS04 --bin-cadence 5min

Each command is generated by :func:`el_paso.cli.recipe_cli.build_recipe_command` from
the recipe's own signature, using the ``CLI_DEFAULTS`` declared in the recipe
module. That is the same builder the recipes' own ``python -m`` entry points use,
so both ways of invoking a recipe expose exactly the same options.
"""

from __future__ import annotations

import ast
import functools
import importlib
import pathlib
from typing import TYPE_CHECKING, NamedTuple

import click
import typer
from rich.console import Console
from rich.table import Table

import el_paso
from el_paso.cli.recipe_cli import build_recipe_command

if TYPE_CHECKING:
    from el_paso.typing import Recipe


class RecipeEntry(NamedTuple):
    """One recipe as it is exposed on the ``el-paso`` command line.

    Attributes:
        mission: The sub-command group the recipe lives in (e.g. ``"poes"``).
        command: The sub-command name within that group (e.g. ``"meped"``).
        module: Import path of the module defining the recipe.
        function: Name of the recipe function inside that module.
    """

    mission: str
    command: str
    module: str
    function: str


RECIPES: tuple[RecipeEntry, ...] = (
    RecipeEntry("arase", "mepe", "el_paso.recipes.arase.process_arase_mepe", "process_arase_mepe"),
    RecipeEntry(
        "arase", "pwe-density", "el_paso.recipes.arase.process_arase_pwe_densities", "process_arase_pwe_density"
    ),
    RecipeEntry("arase", "xep", "el_paso.recipes.arase.process_arase_xep", "process_arase_xep"),
    RecipeEntry(
        "arase", "xep-realtime", "el_paso.recipes.arase.process_arase_xep_realtime", "process_arase_xep_real_time"
    ),
    RecipeEntry("dmsp", "ssj", "el_paso.recipes.dmsp.process_dmsp_ssj_electrons", "process_dmsp_ssj_electrons"),
    RecipeEntry("esa", "ngrm", "el_paso.recipes.esa.process_ngrm_satellite", "process_ngrm_electron_fluxes"),
    RecipeEntry("goes", "mps-high", "el_paso.recipes.goes.process_goes_r_mps_high", "process_goes_r_mps_high"),
    RecipeEntry("goes", "realtime", "el_paso.recipes.goes.process_goes_realtime", "process_goes_real_time"),
    RecipeEntry("gps", "cxd", "el_paso.recipes.gps.process_gps", "process_gps_data"),
    RecipeEntry("poes", "meped", "el_paso.recipes.poes.process_poes_meped", "process_poes_meped_electron"),
    RecipeEntry("poes", "ted", "el_paso.recipes.poes.process_poes_ted", "process_poes_ted_electron"),
    RecipeEntry(
        "probav", "ept-electrons", "el_paso.recipes.probav.process_ept_electron_fluxes", "process_ept_electron_fluxes"
    ),
    RecipeEntry(
        "probav", "ept-protons", "el_paso.recipes.probav.process_ept_proton_fluxes", "process_ept_proton_fluxes"
    ),
    RecipeEntry("rbsp", "ect-combined", "el_paso.recipes.rbsp.process_rbsp_ect_combined", "process_rbsp_ect_combined"),
    RecipeEntry(
        "rbsp",
        "density-combined",
        "el_paso.recipes.rbsp.process_rbsp_efw_emfisis_density_combined",
        "process_rbsp_efw_emfisis_density_combined",
    ),
    RecipeEntry(
        "rbsp", "emfisis-waves", "el_paso.recipes.rbsp.process_rbsp_emfisis_waves", "process_rbsp_emfisis_waves"
    ),
    RecipeEntry(
        "rbsp", "hope-electrons", "el_paso.recipes.rbsp.process_rbsp_hope_electrons", "process_rbsp_hope_electrons"
    ),
    RecipeEntry("rbsp", "hope-protons", "el_paso.recipes.rbsp.process_rbsp_hope_protons", "process_rbsp_hope_protons"),
    RecipeEntry(
        "rbsp",
        "mageis-electrons",
        "el_paso.recipes.rbsp.process_rbsp_mageis_electrons",
        "process_rbsp_mageis_electrons",
    ),
    RecipeEntry(
        "rbsp", "mageis-protons", "el_paso.recipes.rbsp.process_rbsp_mageis_protons", "process_rbsp_mageis_protons"
    ),
    RecipeEntry(
        "rbsp", "rbspice-protons", "el_paso.recipes.rbsp.process_rbsp_rbspice_protons", "process_rbsp_rbspice_protons"
    ),
)


def load_recipe(entry: RecipeEntry) -> tuple[Recipe, dict[str, object]]:
    """Import a recipe and return its function together with its CLI defaults.

    Args:
        entry (RecipeEntry): The registry entry to load.

    Returns:
        tuple[Recipe, dict[str, object]]: The recipe function and the
        ``CLI_DEFAULTS`` declared in its module (an empty dict if it declares none).
    """
    module = importlib.import_module(entry.module)
    return getattr(module, entry.function), getattr(module, "CLI_DEFAULTS", {})


_PACKAGE_ROOT = pathlib.Path(el_paso.__file__).resolve().parent


@functools.cache
def _summary_from_source(module: str, function: str) -> str:
    """Return a function's one-line docstring summary without importing its module.

    Args:
        module (str): Dotted import path of the defining module.
        function (str): Name of the function inside that module.

    Returns:
        str: The first line of the docstring, or an empty string if unreadable.
    """
    source = _PACKAGE_ROOT.joinpath(*module.split(".")[1:]).with_suffix(".py")
    try:
        tree = ast.parse(source.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return ""
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == function:
            return (ast.get_docstring(node) or "").strip().split("\n")[0]
    return ""


def _summary(entry: RecipeEntry) -> str:
    """Return a recipe's one-line summary, read from source without importing it.

    Importing a recipe pulls in its whole scientific stack, which is far too
    expensive to do merely to render a help listing.

    Args:
        entry (RecipeEntry): The registry entry to describe.

    Returns:
        str: The first line of the recipe's docstring, or an empty string if it
        cannot be read.
    """
    return _summary_from_source(entry.module, entry.function)


def _as_click_command(name: str, recipe: Recipe, defaults: dict[str, object]) -> click.Command:
    """Build the Typer command for one recipe and return it as a click command."""
    built = typer.Typer()
    built.command(name=name, no_args_is_help=True)(build_recipe_command(recipe, defaults=defaults))
    command = typer.main.get_command(built)
    # Typer collapses a single-command app into a plain Command rather than a Group.
    if isinstance(command, click.Group):
        command = command.commands[name]
    command.name = name
    return command


class LazyRecipeGroup(click.Group):
    """A mission group that imports a recipe only once it is actually used.

    Building a recipe's command requires its signature, and therefore its import.
    Doing that for every recipe up front costs seconds, so commands are built on
    demand instead.
    """

    def __init__(self, entries: tuple[RecipeEntry, ...], **kwargs: object) -> None:
        """Store the registry entries this group exposes."""
        super().__init__(**kwargs)
        self._entries = {entry.command: entry for entry in entries}

    def list_commands(self, ctx: click.Context) -> list[str]:  # noqa: ARG002
        """Return the command names, without importing any recipe."""
        return sorted(self._entries)

    def get_command(self, ctx: click.Context, cmd_name: str) -> click.Command | None:  # noqa: ARG002
        """Build one recipe's command, importing exactly that recipe."""
        entry = self._entries.get(cmd_name)
        if entry is None:
            return None
        recipe, defaults = load_recipe(entry)
        return _as_click_command(cmd_name, recipe, defaults)

    def format_commands(self, ctx: click.Context, formatter: click.HelpFormatter) -> None:
        """Render the command list from source summaries.

        click's own implementation calls `get_command` for every sub-command just
        to read its short help, which would import every recipe on ``--help``.
        """
        rows = [(name, _summary(self._entries[name])) for name in self.list_commands(ctx)]
        if rows:
            with formatter.section("Commands"):
                formatter.write_dl(rows)


class _RootGroup(click.Group):
    """The top-level group, which also defers building the ``omm`` command."""

    def get_command(self, ctx: click.Context, cmd_name: str) -> click.Command | None:
        """Return a sub-command, building ``omm`` on demand."""
        if cmd_name == "omm":
            return _as_click_command("omm", el_paso.download_omm, {})
        return super().get_command(ctx, cmd_name)

    def list_commands(self, ctx: click.Context) -> list[str]:
        """Return all sub-command names, including the deferred ``omm``."""
        return sorted({*super().list_commands(ctx), "omm"})

    def format_commands(self, ctx: click.Context, formatter: click.HelpFormatter) -> None:
        """Render the command list without building the ``omm`` command.

        As in `LazyRecipeGroup`, click's own implementation would call
        `get_command` for every entry, which for ``omm`` means an import.
        """
        rows = []
        for name in self.list_commands(ctx):
            if name == "omm":
                rows.append((name, _summary_from_source("el_paso.download_omm", "download_omm")))
                continue
            command = super().get_command(ctx, name)
            if command is not None and not command.hidden:
                rows.append((name, command.get_short_help_str()))
        if rows:
            with formatter.section("Commands"):
                formatter.write_dl(rows)


@click.group(
    cls=_RootGroup,
    name="el-paso",
    no_args_is_help=True,
    context_settings={"help_option_names": ["-h", "--help"]},
)
def app() -> None:
    """Download, process and save satellite particle observation data."""


for _mission in sorted({entry.mission for entry in RECIPES}):
    app.add_command(
        LazyRecipeGroup(
            entries=tuple(entry for entry in RECIPES if entry.mission == _mission),
            name=_mission,
            help=f"{_mission.upper()} recipes.",
            no_args_is_help=True,
        )
    )


@app.command("list")
def list_recipes() -> None:
    """List every available recipe."""
    table = Table(title="EL-PASO recipes")
    table.add_column("Command", style="bold cyan", no_wrap=True)
    table.add_column("Module", style="dim", no_wrap=True)
    table.add_column("Description")

    for entry in RECIPES:
        table.add_row(f"el-paso {entry.mission} {entry.command}", entry.module, _summary(entry))

    Console().print(table)


def main() -> None:
    """Run the ``el-paso`` command line application."""
    try:
        app()
    except typer.Abort:
        # Typer's control-flow exceptions are plain RuntimeErrors rather than
        # click exceptions, so click's standalone handler lets them escape. The
        # recipe commands are Typer-built, so they raise these, not click's.
        click.echo("Aborted.", err=True)
        raise SystemExit(1) from None
    except typer.Exit as exit_signal:
        raise SystemExit(exit_signal.exit_code) from None


if __name__ == "__main__":
    main()
